### PR TITLE
A few tweaks to the Android workshop

### PR DESCRIPTION
**Pull request by jkwatson**
Includes adding a bunch of guiding images.

### CODE REVIEW

**Review by mateuszrzeszutek — APPROVED** [review]
There's a couple of images that haven't been used in this PR (add_workflow, workflow_complete) - are they going to be used later or were they added here by mistake?

**Comment by jkwatson** [comment]
> There's a couple of images that haven't been used in this PR (add_workflow, workflow_complete) - are they going to be used later or were they added here by mistake?

Yeah, I captured a few more than I ended up using. I figured they could live here so they wouldn't need to be re-captured if we decided to add a few more screenshots later. I don't feel strongly about it, though, so if you think I should remove them, I can.

**Comment by mateuszrzeszutek** [comment]
The `splunk-otel-android` has contains a specific version (0.8.0) so it might be good idea to remove it anyway, you'd have to create a new image whenever a new version is released. The others: I'm fine with keeping them, as long as they're not confusing anybody.

**Comment by jkwatson** [comment]
> The `splunk-otel-android` has contains a specific version (0.8.0) so it might be good idea to remove it anyway, you'd have to create a new image whenever a new version is released. The others: I'm fine with keeping them, as long as they're not confusing anybody.

Are you saying we should get rid of the screenshot for getting your gradle file set up for the library? Hm. That's also going to be the case for any updates to the core android libraries that are used in here as well (like in the `build_setup.png` image).

**Comment by mateuszrzeszutek** [comment]
> That's also going to be the case for any updates to the core android libraries that are used in here as well (like in the `build_setup.png` image).

Hm, I didn't think of that. We don't really depend strongly on those (like "it won't work with any other version"), do we? Maybe keeping those versions in an image is not that big of a deal.

**Comment by jkwatson** [comment]
> > That's also going to be the case for any updates to the core android libraries that are used in here as well (like in the `build_setup.png` image).
> 
> Hm, I didn't think of that. We don't really depend strongly on those (like "it won't work with any other version"), do we? Maybe keeping those versions in an image is not that big of a deal.

My vote would be to see how painful it ends up being to update the images. We can always remove them if it gets to be too much of a pain to maintain.

I also think it would be good to split up this one big doc into a separate document for each of the steps in the workshop, but I'll do that as a separate PR.

**Pull request merged**
